# Generated by Django 5.1.6 on 2025-06-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_userinfo_best_video_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
