# Generated by Django 5.1.6 on 2025-06-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='years_of_experience',
            field=models.TextField(),
        ),
    ]
