# Generated by Django 5.1.6 on 2025-06-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userinfo_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='resumes/'),
        ),
    ]
