# Generated by Django 5.1.6 on 2025-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='best_video_type',
            field=models.CharField(max_length=100, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submitted At'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='expected_price',
            field=models.CharField(max_length=50, verbose_name='Expected Price'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='experience_level',
            field=models.CharField(max_length=50, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='portfolio_link',
            field=models.URLField(verbose_name='Portfolio URL'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='reason_to_join',
            field=models.TextField(verbose_name='Why do you want to join Editopia Studio?'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='resumes/', verbose_name='Resume / CV'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='software_tools_used',
            field=models.CharField(max_length=255, verbose_name='Primary Editing Software'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weekly_availability',
            field=models.CharField(max_length=50, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='whatsapp_number',
            field=models.CharField(max_length=20, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='years_of_experience',
            field=models.TextField(verbose_name='Experience Description'),
        ),
    ]
