# Generated by Django 5.1.6 on 2025-06-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userinfo_best_video_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
    ]
